### ISSUE TITLE
formatter not working

### ISSUE THREAD

**Issue by letmejustputthishere** [f0i/motoko-format#1]
i installed dprint using 
`brew install dprint`
i run `dprint init` and modified the `dprint.json` to look like this
```
{
  "includes": ["**/*.{mo}"],
  "excludes": [],
  "plugins": [
    "https://gitlab.com/f0i/motoko-format/-/jobs/artifacts/main/raw/release/dprint_plugin_motoko.wasm?job=release&file=plugin.wasm"
  ]
}
```
i installed the dprint vscode plugin and set the default formatter for motoko to `dprint.dprint`

yet, when formatting, nothing happens. is my code already perfectly formatted or did i do something wrong? :D

**Comment by f0i** [comment]
Currently it is most likely that there is some unhanded cases in the formatter that is generating invalid code.
I would recommend waiting a bit until I'm a bit further along with the implementation.

If you want to get more info about what went wrong, you can run dprint from the command line (e.g. `dprint clear-cache && dprint fmt -- path/to/file.mo`)

**Comment by f0i** [comment]
A lot has changed since the date of this issue.
I will close this for now.
Feel free to reopen or add a new issue if there are still problems like this.
